[tool.poetry]
name = "Shop"
version = "0.1.0"
description = "Shop APIs"
authors = ["Blank <rojermen96@gmail.com>"]
license = "BSD-2-Clause license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"
django-ninja = "^1.3.0"
python-dotenv = "^1.0.1"
pillow = "^11.0.0"
celery = "^5.4.0"
django-types = "^0.20.0"
weasyprint = "^64.0"
stripe = "^11.5.0"
django-redis = "^5.4.0"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.4.6"
pylint = "^3.3.4"
flake8 = "^7.1.1"
isort = "^6.0.0"
pre-commit = "^4.1.0"
pylint-django = "^2.6.1"
bandit = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = ["migrations", "node_modules", "__pycache__", "tests"]
pythonVersion = "3.12.8"

[tool.black]
line-length = 90
skip-string-normalization = true
skip-magic-trailing-comma = false
exclude = '''
/(
  migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 90
known_first_party = ["api", "config", "utils", "services"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["*/migrations/*"]

[tool.pylint]
disable = ["C0114", "R0901", "C0115", "C0116", "R0903", "R0801", "E0611", "C0411"]
max-line-length = 90

[tool.pylint.MASTER]
load-plugins = ["pylint_django"]
django-settings-module = "config.settings"
init-hook = """
import sys, os
sys.path.append('.venv/lib/python3.12/site-packages')
sys.path.append(os.path.abspath("src"))
# Pylint does not see the api.view inside the url.
# There is a problem with finding paths inside the service. CRUTCH
#                               VVVVVVVVVV
sys.path.append(os.path.abspath("src/cart"))
"""
ignore-paths = [
  ".*/manage.py",
  ".*/migrations/.*.py$",
  ".venv",
  "^.*.pyi$",
  "^.*_prv_.*$",
  "lib",
  ".*tests/.*",
]

[tool.pylint.REPORTING]
output-format = "colorized"

[tool.bandit]
exclude_dirs = ["tests", "migrations", ".venv"]
tests = ["B101", "B102", "B110", "B404", "B509"]
