# Generated by Django 5.1.4 on 2025-03-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_amount_order_paid_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
