# Generated by Django 5.1.4 on 2025-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('P', 'Pending'),
                    ('R', 'Processing'),
                    ('S', 'Shipped'),
                    ('D', 'Delivered'),
                    ('C', 'Cancelled'),
                ],
                default='P',
                max_length=1,
            ),
        ),
    ]
