name: shop-microservice

networks:
  shop_net:
    name: shop_net

volumes:
  redis_data:
    name: shop_redis_data
  shop_db:
    name: shop_db_data
  rabbitmq_data:
  rabbitmq_logs:

services:
  db:
    image: postgres:${POSTGRES_TAG:-17.2}
    container_name: postgres
    volumes:
      - shop_db:/var/lib/postgresql/data/
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../../.env
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
    healthcheck:
      test: psql -h 0.0.0.0 -U ${POSTGRES_USER:-user-shop} -d ${POSTGRES_DB:-shop} -c 'SELECT 1;'
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shop_net

  redis:
    image: redis/redis-stack:${REDIS_TAG:-7.4.0-v3}
    container_name: redis
    volumes:
      - redis_data:/data
    env_file:
      - ../../.env
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - shop_net

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    labels:
      - "traefik.enable=False"
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shop_net

  cart-service:
    container_name: cart_service
    build:
      context: ../../
      dockerfile: src/cart/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../src/cart/.env
      - ../../.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cart.rule=Host(`api.mysite.com`) && PathPrefix(`/v1/cart`)"
      - "traefik.http.services.cart-service.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/cart"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - shop_net

  catalog-service:
    container_name: catalog_service
    build:
      context: ../../
      dockerfile: src/catalog/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../src/catalog/.env
      - ../../.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog.rule=Host(`api.mysite.com`) && PathPrefix(`/v1/catalog`)"
      - "traefik.http.services.catalog-service.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/catalog"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - shop_net

  # notification-service:
  #   container_name: notification_service
  #   build:
  #     context: ../../
  #     dockerfile: src/notification/Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - ../../src/notification/.env
  #     - ../../.env
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.notification.rule=PathPrefix(`/api/v1/notification`)"
  #     - "traefik.http.services.notification-service.loadbalancer.server.port=8000"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/notification/health"]
  #     interval: 10sj
  #     retries: 5
  #     timeout: 3s
  #   networks:
  #     - shop_net

  orders-service:
    container_name: orders_service
    build:
      context: ../../
      dockerfile: src/orders/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../src/orders/.env
      - ../../.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=Host(`api.mysite.com`) && PathPrefix(`/v1/orders`)"
      - "traefik.http.services.orders-service.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/orders"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - shop_net

  payment-service:
    container_name: payment_service
    build:
      context: ../../
      dockerfile: src/payment/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../src/payment/.env
      - ../../.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=Host(`api.mysite.com`) && PathPrefix(`/v1/payment`)"
      - "traefik.http.services.payment-service.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/payment/docs"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - shop_net

  # users-service:
  #   container_name: users_service
  #   build:
  #     context: ../../
  #     dockerfile: src/users/Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - ../../src/users/.env
  #     - ../../.env
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.users.rule=PathPrefix(`/api/v1/users`)"
  #     - "traefik.http.services.users-service.loadbalancer.server.port=8000"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/users/health"]
  #     interval: 10s
  #     retries: 5
  #     timeout: 3s
  #   networks:
  #     - shop_net

  traefik:
    image: traefik:v3.3
    restart: always
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - shop_net
