## Note: this uses the core `load_definitions` key over
## now deprecated `management.load_definitions`
load_definitions = /etc/rabbitmq/definitions.json

default_user = admin
default_pass = admin

default_vhost = shop_vhost
