# Generated by Django 5.1.4 on 2025-02-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('payment_id', models.PositiveBigIntegerField(unique=True)),
                ('order_id', models.PositiveBigIntegerField(unique=True)),
                ('user_id', models.PositiveBigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_gateway', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('refund_id', models.CharField(max_length=255, unique=True)),
                ('refund_status', models.CharField(max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'remaining_amount',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ('created_refund_at', models.DateTimeField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                (
                    'payment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='refunds',
                        to='api.payment',
                    ),
                ),
            ],
        ),
    ]
